spring:
  application:
    name: onlineshop

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            client-name: Google

  management:
    endpoints:
      web:
        exposure:
          include: health
    endpoint:
      health:
        show-details: never

logging:
  level:
    root: INFO
    com.karpenko.onlineshop: INFO

app:
  init:
    admin:
      email: ${ADMIN_EMAIL}
      password: ${ADMIN_PASSWORD}